### ISSUE TITLE
undefined symbol: Warning

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/sm-ext-TransmitManager#1]
L 08/12/2020 - 12:55:33: [SM] Unable to load extension "TransmitManager.ext": /home/csgocourse/serverfiles/csgo/addons/sourcemod/extensions/TransmitManager.ext.2.csgo.so: undefined symbol: Warning

Ubuntu 18.04 LTS
SM 1.10 6492

**Comment by Bara** [comment]
[sm-ext-TransmitManager.zip](https://github.com/Kxnrl/sm-ext-TransmitManager/files/5112369/sm-ext-TransmitManager.zip)
Compiled against SM1.10 with clang (3.8) on Ubuntu 16.04. [Source](https://github.com/Kxnrl/sm-ext-TransmitManager/tree/90f8323ddc26eba46acdb324a676d20b21773d5a)

**Comment by Kxnrl** [comment]
shoud be fixed in latest
